---
- name: setup facts
  hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
  tasks:
    - import_tasks: tasks/set_dcs_ips.yml
    - import_tasks: tasks/set_pgsql_servers_ips.yml

- name: setup DCS servers
  hosts: dcs_servers
  vars_files:
    - vars.yml
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - import_tasks: tasks/{{ dcs }}.yml

- name: setup HAProxy server
  hosts: haproxy_server
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/haproxy.yml

- name: setup Postgres Servers
  hosts: pgsql_servers
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
      tags:
        - config

  tasks:
    - import_tasks: tasks/consul.yml
      when: dcs == "consul"
    - import_tasks: tasks/postgresql.yml
    - import_tasks: tasks/patroni.yml
