---

- import_tasks: systemd-backports.yml
  when: (ansible_distribution_release == "stretch")

- name: Install patroni package
  package:
    name: patroni
    state: present

- name: Install consul client package
  package:
    name: python3-consul
    state: present
  when: dcs == "consul"

- name: Install zookeeper client package
  package:
    name: python3-kazoo
    state: present
  when: dcs == "zookeeper"

- name: Install etcd3 client package
  package:
    name: python3-etcd3
    state: present
  when: dcs == "etcd3"

- name: Install vip-manager package
  package:
    name: vip-manager
    state: present
  when: vip is defined and vip != "" and dcs == "etcd"

- name: Install vip-manager2 package
  package:
    name: vip-manager2
    state: present
  when: vip is defined and vip != "" and dcs == "etcd3"

- name: Deploy patroni DCS config
  template:
    src: templates/dcs.yml
    dest: /etc/patroni/dcs.yml
    mode: 0640
    owner: "postgres"
    group: "postgres"
  tags:
    - config

- name: Deploy patroni cluster config from template
  template:
    src: templates/config.yml.j2
    dest: /etc/patroni/{{postgresql_major_version}}-{{postgresql_cluster_name}}.yml
    mode: 0640
    owner: "postgres"
    group: "postgres"
  tags:
    - config

- name: systemctl daemon-reload / start patroni
  systemd:
    daemon_reload: yes
    name: patroni@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
    state: restarted
    enabled: yes
  tags:
    - config

- name: systemctl daemon-reload / start vip-manager
  systemd:
    daemon_reload: yes
    name: vip-manager@{{ postgresql_major_version }}-{{ postgresql_cluster_name }}
    state: restarted
    enabled: yes
  when: vip is defined and vip != ""
  tags:
    - config
