- set_fact:
    pgsql_server_ips: "{{ pgsql_server_ips|default([]) + [ hostvars[item].get('intra_address', hostvars[item]['ansible_eth0']['ipv4']['address']) ] }}"
  with_items: "{{ groups['pgsql_servers'] }}"
